// <auto-generated />
using System;
using Example.InterviewQuestion004.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Example.InterviewQuestion004.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818070515_AddOccupationMasterData")]
    partial class AddOccupationMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Example.InterviewQuestion004.Api.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("OccupationId")
                        .HasColumnType("integer")
                        .HasColumnName("occupation_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_base64");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Example.InterviewQuestion004.Api.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("occupations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "software-engineer",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Code = "business-analyst",
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Business Analyst"
                        },
                        new
                        {
                            Id = 3,
                            Code = "quality-assurance",
                            DisplayOrder = 30,
                            IsActive = true,
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ux-ui-designer",
                            DisplayOrder = 40,
                            IsActive = true,
                            Name = "UX/UI Designer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "project-manager",
                            DisplayOrder = 50,
                            IsActive = true,
                            Name = "Project Manager"
                        });
                });

            modelBuilder.Entity("Example.InterviewQuestion004.Api.Models.Profile", b =>
                {
                    b.HasOne("Example.InterviewQuestion004.Api.Models.Occupation", "Occupation")
                        .WithMany("Profiles")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("Example.InterviewQuestion004.Api.Models.Occupation", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
